# reader_for_microxml/Makefile.toml
# https://github.com/sagiegurari/cargo-make/blob/master/src/lib/Makefile.stable.toml

[config]
skip_core_tasks = true

#region: public callable tasks/flows

    [tasks.default]
    description = "show list of public callable tasks"
    clear = true
    command = "cargo"
    args = ["make","--list-all-steps"]

    [tasks.dev]
    description = "cargo build development"
    clear = true
    dependencies = [
        "build_dev",
    ]

    [tasks.release]
    description = "cargo build release"
    clear = true
    dependencies = [
        "build_release",
    ]

    [tasks.doc]
    description = "create docs from comments"
    clear = true
    dependencies = [
		"insert_readme",
        "cargo_doc",
		"doc_copy",
    ]
# endregion


[tasks.build_dev]
clear = true
private = true
description = "build in dev/debug mode"
command = "cargo"
args = ["build"]

[tasks.insert_readme]
clear = true
private = true
description = "copy the content of readme.md into *.rs comments (for the docs)"
script= ["lmake_readme"]

[tasks.cargo_doc]
clear = true
private = true
description = "call cargo doc"
command="cargo"
args=["doc","--no-deps","--document-private-items","--open"]

[tasks.doc_copy]
clear = true
private = true
description = "copy doc folder as docs (out of folder target), so it can be git comitted"
script = [
    "\\rsync -avz --delete-after ~/rustprojects/reader_for_microxml/target/doc/*  ~/rustprojects/reader_for_microxml/docs/"
]

[tasks.build_release]
description = "build for release"
clear = true
private = true
command = "cargo"
args = ["build","--release"]

